### ISSUE TITLE
Upgrade to 0.27

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-alternative_landing#37]
Hola!
Me gustaría poder utilizar este módulo en el decidim-goteo, que está a la versión 0.27, ¿está planificado actualizar este módulo a la 0.27?

¡Gracias!

**Comment by rxnetwalker** [comment]
Es compatible con la 0.27 desde la versión [v0.2.2](https://github.com/Platoniq/decidim-module-alternative_landing/releases/tag/v0.2.2).

**Comment by fblupi** [comment]
This module has been successfully upgraded to 0.27 here: https://github.com/Platoniq/decidim-module-alternative_landing/pull/38
