### ISSUE TITLE
Version 0.25.2 of Decidim is not compatible

### ISSUE THREAD

**Issue by maintainer-partecipa** [Platoniq/decidim-module-alternative_landing#44]
It seems the gem is not compatible with Decidim 0.25.2. Can you please help? BTW: thanks a lot, this gem is very useful.

**Comment by davidbeig** [comment]
Hi!

As you can see in [version.rb](https://github.com/Platoniq/decidim-module-alternative_landing/blob/main/lib/decidim/alternative_landing/version.rb) the main branch works for decidim v0.27.

```ruby
module Decidim
  # This holds the decidim-alternative_landing version.
  module AlternativeLanding
    VERSION = "0.4.0"
    DECIDIM_VERSION = "0.27.2"
    COMPAT_DECIDIM_VERSION = [">= 0.27.0", "< 0.28"].freeze
  end
end
```

Can you try with the [release/0.26-stable](https://github.com/Platoniq/decidim-module-alternative_landing/tree/release/0.26-stable)? It is supposed to work with version 0.25 to 0.26.

**Comment by maintainer-partecipa** [comment]
Hello,

thank you for your kind & quick reply.
I've tried to configure the release 0.26-stable:

gem 'decidim-alternative_landing', git: 'https://github.com/Platoniq/decidim-module-alternative_landing', branch: 'release/0.26-stable'

but it returns an error during webpacker assets compiling:

[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@fullcalendar/core' in '/home/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-alternative_landing-7aeeedc12cd1/app/packs/entrypoints'

**Comment by maintainer-partecipa** [comment]
OK,

should have done
bundle exec rails decidim_alternative_landing:webpacker:install
