### ISSUE TITLE
Latest blog posts content_block shows posts from other organizations

### ISSUE THREAD

**Issue by arusa** [Platoniq/decidim-module-alternative_landing#50]
Because the posts are not filtered by the current organization, the content_block also shows blog posts for other organizations:

https://github.com/Platoniq/decidim-module-alternative_landing/blob/1221cce61ea6ae001bdaaf5e73023a61acf3f6b4/app/cells/decidim/alternative_landing/content_blocks/latest_blog_posts_cell.rb#L23

**Comment by sbrocos** [comment]
@arusa I have problems to reproduce this problem, because :
```
def posts
  @posts ||= Blogs::Post.where(
    component: component || components
  ).limit(posts_to_show).order(created_at: :desc)
end
```
**components** is defined by organization (with current_organization param) and I can't reproduce the situation with component from 2 different organizations

**Comment by arusa** [comment]
It seems updating to the latest version of the module solved the problem 👍
